services:
  masqued:
    build: .
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    privileged: true
    network_mode: host
    environment:
      - GOTRACEBACK=all
      - GODEBUG=cgocheck=0
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./certs:/etc/masqued/certs
      - ./ca:/etc/masqued/ca
      - ./masqued.conf:/etc/masqued/masqued.conf
      - db:/etc/masqued/data
    command: /run.sh
volumes:
    db:
