services:
  masque-server:
    build: .
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 443:443/udp
    volumes:
      - ./certs:${CERT_DIR}
      - ./ca:${CA_DIR}
    command: /run.sh
